# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import tutoring_pb2 as tutoring__pb2

GRPC_GENERATED_VERSION = '1.66.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in tutoring_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TutoringStub(object):
    """Tutoring Service to generate answers
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getLLMAnswerResponse = channel.unary_unary(
                '/Tutoring/getLLMAnswerResponse',
                request_serializer=tutoring__pb2.LLMRequest.SerializeToString,
                response_deserializer=tutoring__pb2.LLMResponse.FromString,
                _registered_method=True)


class TutoringServicer(object):
    """Tutoring Service to generate answers
    """

    def getLLMAnswerResponse(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TutoringServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getLLMAnswerResponse': grpc.unary_unary_rpc_method_handler(
                    servicer.getLLMAnswerResponse,
                    request_deserializer=tutoring__pb2.LLMRequest.FromString,
                    response_serializer=tutoring__pb2.LLMResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Tutoring', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('Tutoring', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Tutoring(object):
    """Tutoring Service to generate answers
    """

    @staticmethod
    def getLLMAnswerResponse(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Tutoring/getLLMAnswerResponse',
            tutoring__pb2.LLMRequest.SerializeToString,
            tutoring__pb2.LLMResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
